### ISSUE TITLE
Zero install not working for me

### ISSUE THREAD

**Issue by divs1210** [PEZ/rich4clojure#9]
### This is what I'm seeing

<img width="1436" alt="Screenshot 2021-08-17 at 1 52 26 PM" src="https://user-images.githubusercontent.com/3773773/129691546-56eac5c5-82ac-4d5a-8da1-c5a2402054a3.png">

### These are the errors in the web console:

```
Firefox can’t establish a connection to the server at ws://localhost:63100/localapp.LocalApp/TunnelStatus. reconnecting-websocket-mjs.js:517:18

Firefox can’t establish a connection to the server at ws://localhost:63100/localapp.LocalApp/TunnelStatus. reconnecting-websocket-mjs.js:517:18

Uncaught (in promise) NoRef (UserDataSyncError) syncResource:unknown operationId:b6fcbf29-095c-4dec-b273-b40f5fd2cf6f: Server did not return the ref
    o userDataSync.ts:250
    s userDataSync.ts:258
    read userDataSyncStoreService.ts:295
    extensionsPreviewInitializerPromise userDataInit.ts:226
    getExtensionsPreviewInitializer userDataInit.ts:227
    initializeInstalledExtensionsPromise userDataInit.ts:195
    initializeInstalledExtensions userDataInit.ts:197
    Ha extensionService.ts:79
    promise callback*Ha extensionService.ts:78
    _createInstance instantiationService.ts:110
    _createServiceInstance instantiationService.ts:230
    _createServiceInstanceWithOwner instantiationService.ts:219
    _createAndCacheServiceInstance instantiationService.ts:208
    _safeCreateAndCacheServiceInstance instantiationService.ts:151
    _getOrCreateServiceInstance instantiationService.ts:135
    get instantiationService.ts:54
    initLayout layout.ts:255
    startup workbench.ts:141
    invokeFunction instantiationService.ts:61
    startup workbench.ts:134
    open web.main.ts:97
    se web.main.ts:389
    g workbench.web.api.ts:544
    V workbench.ts:616
    me workbench.ts:228
    start workbench.ts:774
    c ide-frontend-service-impl.js:31
    set ide-frontend-service-impl.js:79
    <anonymous> workbench.ts:774
    _invokeFactory loader.js:1136
    complete loader.js:1146
    _onModuleComplete loader.js:1772
    _onModuleComplete loader.js:1784
    _resolve loader.js:1732
    defineModule loader.js:1375
    o loader.js:1660
    v loader.js:2167
    _invokeFactory loader.js:1136
    complete loader.js:1146
    _onModuleComplete loader.js:1772
    _onModuleComplete loader.js:1784
    _resolve loader.js:1732
    defineModule loader.js:1375
    p loader.js:1822
    <anonymous> workbench.nls.js:7
userDataSync.ts:250:2

Firefox can’t establish a connection to the server at ws://localhost:63100/localapp.LocalApp/TunnelStatus. reconnecting-websocket-mjs.js:517:18

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://open-vsx.org/vscode/gallery/extensionquery. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://open-vsx.org/vscode/gallery/extensionquery. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://open-vsx.org/vscode/gallery/extensionquery. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://open-vsx.org/vscode/gallery/extensionquery. (Reason: CORS request did not succeed).

Firefox can’t establish a connection to the server at ws://localhost:63100/localapp.LocalApp/TunnelStatus. reconnecting-websocket-mjs.js:517:18

Firefox can’t establish a connection to the server at ws://localhost:63100/localapp.LocalApp/TunnelStatus. reconnecting-websocket-mjs.js:517:18

could not connect to local app 5 times, giving up, use 'Gitpod: Connect to Local App' command to retry workbench.ts:459:13
```

**Comment by PEZ** [comment]
Thanks for reporting. Looks like a CORS problem with the open-vsx repository prevents Calva from being installed. Can you check in the **Extensions** pane if Calva is even there?

**Comment by PEZ** [comment]
I find this closed issue on Gitpod as my only clue right now: https://github.com/gitpod-io/gitpod/issues/4460 

I'm also asking for help in their Discord, let's hope we can find out how to fix this!

**Comment by pawlean** [comment]
Let me look into this and ask internally @PEZ!

**Comment by PEZ** [comment]
Awesome, @pawlean!

**Comment by akosyakov** [comment]
@divs1210 Do you use any firewalls or adblocking software? Some of them remove etags and it breaks browser caching, see: https://github.com/gitpod-io/gitpod/issues/4391#issuecomment-889545562

**Comment by akosyakov** [comment]
CORS issues are irrelevant, if VS Code cannot pull extension through the browser, it works around CORS on the backend.

**Comment by divs1210** [comment]
Actually yes, I do use uBlock Origin and ClearURLS.

I will disable them and try again and let you folks know.

**Comment by divs1210** [comment]
@akosyakov ClearURLS was causing the issues.

On disabling it, the editor loads just fine - I'm seeing code highlighting and can start a REPL.

**Comment by PEZ** [comment]
Awesome news! I will update the instructions/readme for the Rich 4Clojure repository with this info.
